// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT42J4asVTyc9K7biZV3lHUxYaaBfrIu0',
    appId: '1:612348683346:web:bdeb52c285b9cfee586b8b',
    messagingSenderId: '612348683346',
    projectId: 'lifecoachapp-upgraded',
    authDomain: 'lifecoachapp-upgraded.firebaseapp.com',
    storageBucket: 'lifecoachapp-upgraded.firebasestorage.app',
    measurementId: 'G-TTZYBN3Y03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8OhMFM-1CRLvkoOIpqhR6qs6XKu3tBk',
    appId: '1:612348683346:android:846800ce3ac2d694586b8b',
    messagingSenderId: '612348683346',
    projectId: 'lifecoachapp-upgraded',
    storageBucket: 'lifecoachapp-upgraded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jY4cTdth1ile87b-9M71eiiPB75RANI',
    appId: '1:612348683346:ios:9611def4c273e3e2586b8b',
    messagingSenderId: '612348683346',
    projectId: 'lifecoachapp-upgraded',
    storageBucket: 'lifecoachapp-upgraded.firebasestorage.app',
    iosBundleId: 'com.example.lifecoachAppUpgraded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jY4cTdth1ile87b-9M71eiiPB75RANI',
    appId: '1:612348683346:ios:9611def4c273e3e2586b8b',
    messagingSenderId: '612348683346',
    projectId: 'lifecoachapp-upgraded',
    storageBucket: 'lifecoachapp-upgraded.firebasestorage.app',
    iosBundleId: 'com.example.lifecoachAppUpgraded',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT42J4asVTyc9K7biZV3lHUxYaaBfrIu0',
    appId: '1:612348683346:web:435d04df71f7c548586b8b',
    messagingSenderId: '612348683346',
    projectId: 'lifecoachapp-upgraded',
    authDomain: 'lifecoachapp-upgraded.firebaseapp.com',
    storageBucket: 'lifecoachapp-upgraded.firebasestorage.app',
    measurementId: 'G-R1Q7G5S7P0',
  );
}
